config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'home', to: 'static_pages#home'

  get 'portfolio', to: 'static_pages#portfolio'

  get 'about', to: 'static_pages#about'

  get 'contact', to: 'static_pages#contact'

  get 'resume', to: 'static_pages#resume'

  post 'contact_create', to: 'static_pages#contact_create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @page_name = "home"
  end

  def resume
    @page_name = "resume"
  end

  def portfolio
    @page_name = "portfolio"
  end

  def about
    @page_name = "about"
  end

  def contact
    @page_name = "contact"
  end

  def contact_create
    if contact_params[:firstname].blank? || contact_params[:lastname].blank? || contact_params[:email].blank? || contact_params[:message].blank?
      flash[:warning] = "Please fill all the fields before sending a message."
      redirect_to contact_path
    else
      ContactMailer.contact_mail(contact_params[:firstname], contact_params[:lastname], contact_params[:email], contact_params[:message]).deliver_later
      flash[:notice] = "Message sent!"
      redirect_to contact_path
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:firstname, :lastname, :email, :message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<div class="ui vertical footer segment bottom fixed">
    <div class="ui container">
      <div class="ui stackable inverted divided equal height stackable grid">
        <div class="four wide column footer-column">
          <h4 class="ui inverted header .lato-font footer-header">Links & contact</h4>
          <div class="ui inverted link list">
            <a href="https://www.linkedin.com/in/amandine-pasin-9750b512a/" class="item footer-link">Linkedin</a>
            <a href="https://github.com/coconatsuki" class="item footer-link">Github page</a>
            <%= link_to "Contact me", contact_path, class: "item footer-link" %>
          </div>
        </div>
        <div class="four wide column footer-column">
          <h4 class="ui inverted header .lato-font footer-header">Favorite learning resources</h4>
          <div class="ui inverted link list">
            <a href="https://www.theodinproject.com/" class="item footer-link">The Odin Project</a>
            <a href="https://www.codeschool.com" class="item footer-link">Codeschool</a>
            <a href="http://www.codewars.com" class="item footer-link">Codewars</a>
          </div>
        </div>
        <div class="seven wide column footer-column">
          <h4 class="ui inverted header .lato-font footer-header">Personal blog</h4>
          <p class="blog">If you are interested in Japan and can read french, have a look at my blog!</p>
          <a href="https://unefourmiatokyo.com" class="item footer-link" id="fourmi">Une fourmi à Tokyo</a>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/_head.html.erb
<link href="https://fonts.googleapis.com/css?family=Crimson+Text|Lato" rel="stylesheet"> 
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
<title>Amandine Pasin</title>
<%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_nav.html.erb
<div class="nav">
  <div class="ui tabular fixed stackable menu nav-links align-center">
    <%= link_to "Amandine Pasin", root_path, id: "logo" %>
    <%= link_to "Home", root_path, class: "item right nav #{"active" if @page_name == "home"}" %>
    <%= link_to "Resume", resume_path, class: "item nav #{"active" if @page_name == "resume"}" %>
    <%= link_to "Portfolio", portfolio_path, class: "item nav #{"active" if @page_name == "portfolio"}" %>
    <%= link_to "About", about_path, class: "item nav #{"active" if @page_name == "about"}" %>
    <%= link_to "Contact", contact_path, class: "item nav #{"active" if @page_name == "contact"}" %>
  </div>
</div>

<div class="ui fixed stackable menu colored-nav mobile-nav" id="mobile-nav">
  <%= link_to "Amandine Pasin", root_path, id: "logo" %>
<div class="ui dropdown flex flex-column justify-center" id="menu-dropdown">
  <div class="text menu-element flex flex-column">
    <span class="flex menu-component"></span>
    <span class="flex menu-component"></span>
    <span class="flex menu-component"></span>
  </div>
    <div class="ui menu nav-links align-center colored-nav">
      <%= link_to "Home", root_path, class: "item right nav #{"active" if @page_name == "home"}" %>
      <%= link_to "Resume", resume_path, class: "item nav #{"active" if @page_name == "resume"}" %>
      <%= link_to "Portfolio", portfolio_path, class: "item nav #{"active" if @page_name == "portfolio"}" %>
      <%= link_to "About", about_path, class: "item nav #{"active" if @page_name == "about"}" %>
      <%= link_to "Contact", contact_path, class: "item nav #{"active" if @page_name == "contact"}" %>
    </div>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/head' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <div class="ui container main flex flex-column flex-between all-pages-container">
      <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/static_pages/about.html.erb
<main class=" page-container about-container about-page-container">
  <div class="ui segment about-page">
  <div class="first-about-row flex align-center">
    <div class="ui medium left floated image" id="about-photo">
      <%= image_tag("profil-about.jpg") %>
    </div>
  <div class="content about-content">
      <div class="first-subtitle-container flex">
        <h2 class="header subtitle crimson-font">What I'm doing now</h2>
      </div>
      <div class="meta">
        <p>Hello, I'm Amandine and I'm a programmer.</p>
        <p>My favorite frameworks are React.js and Ruby on Rails, and I mainly use Javascript and Ruby as server side programming languages.</p>
        <p>Before programming, I worked as a journalist, a translator/interpreter and a french teacher for foreign people.</p>
        <p>Becoming a web developer is a big change of career but after all, computer programming is just another foreign language!
            Except that you communicate with a much dummier and stubborn individual (that is, your computer).</p>
      </div>
    </div>
</div>
  <div class="content about-content">
        <div class="meta">

          <h2 class="header subtitle crimson-font second-subtitle">Why becoming a programmer?</h2>

          <p>I began my career in France, spent 3 years in Japan (<a href="www.unefourmiatokyo.com">checkout my blog!</a>), then 2 years in Montreal, and I'm now back to Kyoto.</p>
          <p>Some months after working as a french teacher in Canada, I felt that I wasn't learning and growing anymore.
            It was my 4th year as a teacher when I realized I wanted something new and more challenging.</p>
         
          <p class="last-paragraph">Then, my partner and some friends suggested me to learn programming, and so I did. They were totally right when they said it's a very challenging and rewarding job!</p>
         
          <h2 class="header subtitle crimson-font third-subtitle">When I'm not studying</h2>

          <p>My favorite hobby is probably dancing. I'm also fond of photography and hiking.</p>
          <p>To relax at home, I read a lot and play video games.<br />
             I also spend time learning and practicing foreign languages, especially japanese.</p>
          <p>Finally, one of my great pleasures is drinking tea in some 'Salon de thé' and try out some exotic restaurant!</p>
          <p>Feel free to say hi if you have some common interests.</p>
          <p>Thank you for reading! </p>
        </div>
      </div>
  </div>
</main>

app/views/static_pages/contact.html.erb
<main class="page-container contact-page-container">
<div class="ui segment contact-page">
  <header class="flex flex-column text-center contact-header">
    <h1 class="crimson-font">You have a question? A job offer for me?</h1>
    <h3 class="crimson-font">Please send me a message and I'll answer quickly.</h1>
  </header>

  <%= form_for(:contact, url: contact_create_path, html: {class: "ui form flex justify-center flex-column align-center"}) do |f| %>
    <div class="flex flex-column contact-form">
      <div class="required field">
        <label>Name</label>
        <div class="two fields">
          <div class="field">
            <%= f.text_field :firstname, placeholder: "First Name" %>
          </div>
        <div class="field">
          <%= f.text_field :lastname, placeholder: "Last Name" %>
        </div>
      </div>
    </div>

    <div class="required field">
      <label>Email</label>
      <div class="field">
        <%= f.email_field :email, placeholder: "Email address" %>
      </div>
    </div>

    <div class="required field">
      <label>Message</label>
      <%= f.text_area :message, rows: 6 %>
    </div>
    <%= f.submit "Send message", class: "ui submit button fluid positive contact-submit"  %>
  </div>
  <% end %>

</div>
</main>

app/views/static_pages/home.html.erb
<main class="home-page-container">
    <section class="first-home-row"> 
      <div class="left-picture"></div>
      <div class="text-column">
        <div class="profile">
          <div class="profile-photo">
            <%= image_tag("profil.jpg", class: "ui segment medium circular image") %>
          </div>
          <div class="photo-caption flex flex-column">
            <h1 class="header-name title">Amandine Pasin</h1>
            <ul class="header-links flex justify-around">
             <li><a href="https://github.com/"><i class="big-icon" id="github"></i></a></li>
             <li><a href="https://www.linkedin.com/in/amandine-pasin-9750b512a/"><i class="big-icon" id="linkedin"></i></a></li>
             <li><a href="https://unefourmiatokyo.com/"><i class="big-icon" id="wordpress"></i></a></li>
           </ul>
          </div>
       </div>
      <div class="ui tall stacked segment salutation">
        <p class="introduction text-center intro-title">Hi, I'm Amandine.</p>
        <p class="introduction">I'm a <strong>Full Stack Developer</strong>, and I like to build <strong>efficient and enjoyable apps/websites</strong>, with a modern and elegant design.</p>
        <p class="introduction">If you have a new project in mind, or an existing website that needs a fresher design or new features, I'd be glad to help!</p>
        <p class="introduction">I'm now <strong>open to Freelance missions or remote positions.</strong>If interested, please contact me. I always answer quickly to all requests.</p>
      </div>

       <div class="arrow-container">
         <div class="arrow bounce">
           <i class="fa fa-arrow-down fa-5x" aria-hidden="true">
           </i>
        </div>
      </div>

     <div class="presentation ui tall stacked segment">
       <p class="introduction intro-title text-center">Why choosing me?</p>
       <p class="introduction"><strong>I'm used to work on all aspects of a project</strong>, from HTML/CSS integration to Back-End programming, including the CI/CD process and deployment.</p>
       <p class="introduction">Also, <strong>I'm really professional, patient and always attentive to my clients requirements</strong>. I like my job and I like doing it well. If you're satisfied, I am too!</p>
       <p  class="introduction">To get a better idea of what I can do, please have a look at my Portfolio.</presentation-text>
    </div>
    </div>
  </section>
  <section class="ui piled segment news-container">
    <h3 class="news text-center">Skills and Techs</h3>
    <div class="ui celled list">
      <div class="item news-items">
      <div class="content news-content">
      <div class="header">Programming languages</div>
        Ruby, Javascript (ES6), SQL
      </div>
    </div>
    <div class="item news-items">
      <div class="content news-content">
        <div class="header">Frameworks</div>
          Ruby on Rails, Node.js, React.js
        </div>
      </div>
    <div class="item news-items">
    <div class="content news-content">
      <div class="header">Web techs</div>
        HTML5/CSS3, Sass, Javascript (ES6), GatsbyJS, jQuery, Apollo/Prisma, Rest API, graphQL
      </div>
    </div>
    <div class="item news-items">
      <div class="content news-content">
        <div class="header">Test frameworks</div>
          Rspec, Jest, Enzyme
        </div>
      </div>
      <div class="item news-items">
        <div class="content news-content">
          <div class="header">CSS Framework and utilities</div>
            Bootstrap, Semantic UI, Emotion, styled-component
          </div>
        </div>
        <div class="item news-items">
          <div class="content news-content">
            <div class="header">Version Control System & Deployment</div>
              Git, Github, Heroku
            </div>
          </div>
          <div class="item news-items">
            <div class="content news-content">
            <div class="header">Languages</div>
              French (native), English (Business Level), Japanese (Business Level)
            </div>
          </div>
        </div>
    </section>
</main>